server:
  port: 8763
#  context-path: /member
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
spring:
  application:
    name: netty
  redis:
    host: 140.82.46.90
    password:
    port: 6379
    pool:
      max-idle: 100
      min-idle: 1
      max-active: 1000
      max-wait: -1
  #数据库连接信息
  datasource:
    name: test
#    url: jdbc:mysql://140.82.46.90:3306/jzr-member
    url: jdbc:mysql://140.82.46.90:3306/jzr_medical?useUnicode=true&useSSL=false&autoReconnect=true&characterEncoding=UTF-8&queryInterceptors=com.jzr.common.LogSqlQueryInterceptor&serverTimezone=GMT%2B8
#    url: jdbc:mysql://140.82.46.90:3306/jzr_medical?useUnicode=true&useSSL=false&autoReconnect=true&characterEncoding=UTF-8&serverTimezone=GMT%2B8
    username: rock
    password: 123456
    # 使用druid数据源
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    filters: stat
    maxActive: 20
    initialSize: 1
    maxWait: 60000
    minIdle: 1
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: select 'x'
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxOpenPreparedStatements: 20

